# Generated by Django 5.0.4 on 2024-08-13 18:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('link', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Item em Estoque', 'verbose_name_plural': 'Itens em Estoque'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CEP inválido. Por favor, use o formato: XXXXX-XXX', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.EmailValidator(message='Coloque um endereço válido.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_session',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='ID da Sessão'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Por favor, use o formato: +55 (XX) XXXX-XXXX ou +55 (XX) XXXXX-XXXX', regex='^\\+55 \\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código de Transação'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.stockitem', verbose_name='Item em Estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.type', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='color',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='size',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
    ]
