# Generated by Django 5.0.4 on 2024-08-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.color', verbose_name='Cor'),
        ),
    ]
