# Generated by Django 5.1 on 2024-08-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_alter_color_options_alter_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='amount',
            new_name='quantity',
        ),
    ]
