# Generated by Django 5.1 on 2024-08-15 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Por favor, use um dos formatos permitidos: +55 (XX) XXXX-XXXX, +55 (XX) XXXXX-XXXX, (XX) XXXX-XXXX, (XX) XXXXX-XXXX, XX XXXX-XXXX, XX XXXXX-XXXX, ou XX XXXXXXXXX', regex='^(?:\\+55\\s)?(?:\\(\\d{2}\\)\\s|\\d{2}\\s)?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
