# Generated by Django 5.1 on 2024-10-24 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='pslug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CEP inválido. Por favor, use o formato: XXXXX-XXX ou XXXXXXXX', regex='^\\d{5}-\\d{3}$|^\\d{8}$')], verbose_name='CEP'),
        ),
    ]
