# Generated by Django 5.1 on 2024-11-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_rename_pslug_type_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id_session',
            new_name='session_id',
        ),
    ]
