# Generated by Django 5.1 on 2024-11-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_alter_banner_link_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
